[package]
name = "rust-multisig-2-of-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = "0.29.0"
dirs-next = "2.0"
bitcoin_scripts = "0.10.0"